services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: cog
    ports: ["3307:3306"]
    volumes:
      - ../init/mysql:/docker-entrypoint-initdb.d
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-image=FULL
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:3.6
    depends_on: [zookeeper]
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports: ["9092:9092"]

  connect:
    image: debezium/connect:2.5
    depends_on: [kafka]
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    ports: ["8083:8083"]

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on: [kafka]
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports: ["9000:9000"]

  # --- Hive Metastore stack ---
  metastore-db:
    image: postgres:15
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepw
      POSTGRES_DB: metastore
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    volumes:
      - metastore-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:ro

  hive-metastore:
    image: apache/hive:3.1.3
    platform: linux/amd64
    depends_on: [metastore-db]
    ports: ["9083:9083"]
    command: ["/opt/hive/bin/hive","--service","metastore","-p","9083"]
    volumes:
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      - ../:/lakehouse




  # --- Trino ---
  trino:
    image: trinodb/trino:latest
    depends_on: [hive-metastore]
    ports: ["8080:8080"]
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog
      - ../:/lakehouse

volumes:
  metastore-data: